name: testing matrix
on: workflow_dispatch

env:
  REGISTRY: "ghcr.io/${{ github.actor }}"

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./test.json)" >> $GITHUB_OUTPUT
  patch:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        images: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: CurrentTag 
        run: | 
            CURRENT_TAG="${{ matrix.images.current_tag}}"
            echo  "current tag is: $CURRENT_TAG"
      - name: NextTag 
        run: | 
            NEXT_TAG="${{ matrix.images.next_tag}}"
            echo  "Next tag will be: $NEXT_TAG"